# Generated by Django 4.2.2 on 2023-07-02 21:08

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='user_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
